name: foxy_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  chewie:
  provider:
  path_provider:
  permission_handler:
  font_awesome_flutter: 10.7.0
  list_all_videos: ^1.2.0
  on_audio_query: ^2.9.0
  just_audio: ^0.9.20
  video_player: ^2.8.5
  # just_audio_background:
  # audio_service:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:
  flutter_native_splash:

flutter:
  uses-material-design: true
  assets:
    - assets/
